// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rdirichlet
arma::mat rdirichlet(int n, arma::vec a);
RcppExport SEXP _dist_rdirichlet(SEXP nSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(rdirichlet(n, a));
    return rcpp_result_gen;
END_RCPP
}
// rdiscrete
arma::mat rdiscrete(int n, arma::vec p, bool as_indicator);
RcppExport SEXP _dist_rdiscrete(SEXP nSEXP, SEXP pSEXP, SEXP as_indicatorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type as_indicator(as_indicatorSEXP);
    rcpp_result_gen = Rcpp::wrap(rdiscrete(n, p, as_indicator));
    return rcpp_result_gen;
END_RCPP
}
// rgem
arma::mat rgem(int n, int k, double b);
RcppExport SEXP _dist_rgem(SEXP nSEXP, SEXP kSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rgem(n, k, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dist_rdirichlet", (DL_FUNC) &_dist_rdirichlet, 2},
    {"_dist_rdiscrete", (DL_FUNC) &_dist_rdiscrete, 3},
    {"_dist_rgem", (DL_FUNC) &_dist_rgem, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
