# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sample from the Dirichlet distribution
#'
#' @param n number ofsample
#' @param a vector of weights
#'
#' @export
rdirichlet <- function(n, a) {
    .Call(`_dist_rdirichlet`, n, a)
}

#' Sample from the discrete distribution
#'
#' @param n number of samples
#' @param p vector of class probabilities, must sum to 1
#' @param as_indicator false: returns class number, true: returns binary vector
#'
#' @export
rdiscrete <- function(n, p, as_indicator = FALSE) {
    .Call(`_dist_rdiscrete`, n, p, as_indicator)
}

#' Sample from the GEM distribution
#'
#' @param n number of samples
#' @param k vector size 
#' @param b shape
#'
#' @export
rgem <- function(n, k, b) {
    .Call(`_dist_rgem`, n, k, b)
}

